import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/_layout/navbar";
import { headers } from "next/headers"; // added
// import ContextProvider from "@/context";
import Providers from "@/providers/privy-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Await headers and extract cookies
  const headersList = await headers();
  const cookies = headersList.get('cookie');

  return (
    <html lang="en">
      <body>
        {/* <ContextProvider cookies={cookies}> */}
        <Providers>

          <Navbar />
          <main className="min-h-screen bg-background pt-16">
            {children}
          </main>

        </Providers>
        {/* </ContextProvider> */}
      </body>
    </html>
  );
}
