import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/_layout/navbar";
import { headers } from "next/headers"; 
import ContextProvider from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Await headers and extract cookies
  const headersList = await headers();
  const cookies = headersList.get('cookie');

  return (
    <html lang="en">
      <body>
        <ContextProvider cookies={cookies}>
          <Navbar />
          <main className="min-h-screen bg-background pt-16">
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
